In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import KernelPCA
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [2]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

In [77]:
def kpca(indep_X,components):
    kpca_model = KernelPCA(n_components=components, kernel = 'rbf')
    X_train = kpca_model.fit_transform(indep_X)
  
    return X_train

In [78]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm

In [79]:
def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [80]:
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [81]:
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [82]:
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [83]:
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [84]:
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [85]:
def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [86]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe.loc[idex, 'Logistic'] = acclog[number]
        dataframe.loc[idex, 'SVMl'] = accsvml[number]
        dataframe.loc[idex, 'SVMnl'] = accsvmnl[number]
        dataframe.loc[idex, 'KNN'] = accknn[number]
        dataframe.loc[idex, 'Navie'] = accnav[number]
        dataframe.loc[idex, 'Decision'] = accdes[number]
        dataframe.loc[idex, 'Random'] = accrf[number]
    return dataframe

In [87]:
dataset1=pd.read_csv("prep.csv",index_col=None)

df2=dataset1

df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', axis=1)
dep_Y=df2['classification_yes']

In [111]:
kpca_=kpca(indep_X, 1)       

acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [112]:
kpca_

array([[-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393299],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393299],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393375],
       [-0.00393288],
       [-0.00393288],
       [-0.00393289],
       [-0.00393288],
       [-0.00393695],
       [-0.00393288],
       [-0.00393452],
       [-0.00393288],
       [-0.00393288],
       [-0.00393452],
       [-0.00393288],
       [-0.00393308],
       [-0.00393288],
       [-0.00393288],
       [-0.00394986],
       [-0.00393288],
       [-0.00393288],
       [-0.00393699],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393305],
       [-0.00393288],
       [-0.00393288],
       [-0.00393695],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393289],
       [-0.00393288],
       [-0.00393288],
       [-0.00402272],
       [-0.0041488 ],
       [-0.00393375],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393291],
       [-0.00393301],
       [-0.00393288],
       [-0.00393314],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393295],
       [-0.00393288],
       [-0.00393288],
       [-0.00393308],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00394421],
       [-0.00393783],
       [-0.00393288],
       [-0.00394117],
       [-0.00393288],
       [-0.00393783],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00394995],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393514],
       [-0.00393288],
       [-0.00393288],
       [-0.00393314],
       [-0.00393288],
       [-0.00393288],
       [-0.00393506],
       [-0.00393289],
       [-0.00393288],
       [-0.00393292],
       [-0.00393288],
       [-0.00393551],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393289],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00413118],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00397351],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [ 0.01680973],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393289],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393291],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393363],
       [-0.0039335 ],
       [-0.00393287],
       [-0.00393288],
       [-0.0039397 ],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00394118],
       [-0.00393288],
       [ 0.77374729],
       [-0.00393401],
       [-0.00393288],
       [-0.00555591],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00394298],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393297],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393292],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00394298],
       [-0.00393399],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393318],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393283],
       [-0.00393288],
       [-0.00393288],
       [-0.00503364],
       [-0.00393288],
       [-0.00393288],
       [ 0.77355449],
       [-0.00393288],
       [-0.00393307],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393325],
       [-0.00393288],
       [-0.00393288],
       [-0.00417953],
       [-0.00394336],
       [-0.00538388],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393291],
       [-0.00393288],
       [-0.00393288],
       [-0.00417953],
       [-0.00393353],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00395228],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393353],
       [-0.00393609],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00502722],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.0039344 ],
       [-0.00393288],
       [-0.00394119],
       [-0.00393288],
       [-0.00393288],
       [-0.00382974],
       [-0.00393288],
       [-0.0026804 ],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393307],
       [-0.00393288],
       [-0.00421641],
       [-0.00393288],
       [-0.00393288],
       [-0.00393309],
       [-0.00393288],
       [-0.00393288],
       [-0.00394119],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393298],
       [-0.00430828],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393328],
       [-0.00393328],
       [-0.00394124],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393578],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00417171],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00394124],
       [-0.00393288],
       [-0.00393288],
       [-0.00393294],
       [-0.00393288],
       [-0.00428782],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393288],
       [-0.00393299],
       [-0.00421438],
       [-0.00393288],
       [-0.00393289],
       [-0.00393288],
       [-0.00393536],
       [-0.00393288]])

In [113]:
X_train, X_test, y_train, y_test=split_scalar(kpca_,dep_Y)   
    
        
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Diwali 6\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [102]:
result
#4

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.64  0.64  0.64  0.54  0.39     0.68   0.67

In [98]:
result
#3

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.64  0.64  0.64  0.54  0.39     0.68   0.68

In [106]:
result
#5

          Logistic  SVMl SVMnl  KNN Navie Decision Random
ChiSquare     0.64  0.64  0.64  0.6  0.39     0.68   0.65

In [94]:
result
#2

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.64  0.64  0.64  0.58  0.39      0.7   0.69

In [110]:
result
#6

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.64  0.64  0.64  0.51  0.39     0.69   0.68

In [114]:
result
#1

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.64  0.64  0.64  0.57  0.38     0.69   0.69